apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consul2dogstats
  labels:
    project: consul2dogstats
    role: app
spec:
  replicas: 2
  selector:
    matchLabels:
      project: consul2dogstats
      role: app
  template:
    metadata:
      labels:
        project: consul2dogstats
        role: app
    spec:
      containers:
      - name: consul2dogstats
        image: docker-registry.zende.sk/consul2dogstats:latest
        env:
        - name: CONSUL_HTTP_ADDR
          value: 169.254.1.1:8500
        - name: DATADOG_API_KEY
          valueFrom:
            secretKeyRef:
              name: datadog
              key: token
